runtime: nodejs20

service: league-manager-web

handlers:

- url: /(.*\.(gif|png|jpg|css|js|woff|woff2|ttf|eot|svg|ico)(|\.map))$
  static_files: dist/league-manager-web/\1
  upload: dist/league-manager-web/(.*\.(gif|png|jpg|css|js|woff|woff2|ttf|eot|svg|ico)(|\.map))$

- url: /assets/(.*)
  static_files: dist/league-manager-web/assets
  upload: dist/league-manager-web/assets/(.*)

- url: /(.*)
  static_files: dist/league-manager-web/index.html
  upload: dist/league-manager-web/index.html